### ISSUE TITLE
support for generic types

### ISSUE THREAD

**Issue by droundy** [djc/askama#111]
I'd love to see support for deriving `Template` on generic types.  I don't think this should be too hard, either!  :)  The idea is to be able to do something like:

```
#[derive(Template, Serialize, Deserialize, Clone, Ord, PartialOrd, Eq, PartialEq)]
#[template(path = "choices.html")]
pub struct Choices<T> {
    pub current: T,
    pub possibility: Vec<T>,
    pub choice_name: String,
}
```
where `choices.html` will create an html select block.  I think this is a reasonable design choice, and one that would work well with askama's design.

I've implemented [something similar for clapme](https://github.com/droundy/clapme/blob/master/clapme_derive/src/lib.rs#L453) if an example would help.  I just add a constraint that any type parameters must implement `ClapMe`, and I think you could do the same with `Display`.  I can't guarantee that my clapme code is the best approach (or even bug-free), as I'm new to the business of derive macros, but it seems to work.

Thoughts?

**Comment by djc** [comment]
So this already mostly works -- Askama copies trait bounds from the struct definition:

https://github.com/djc/askama/blob/master/testing/tests/simple.rs#L149

I don't think I want Askama to generate the trait bounds because templates are pretty flexible and can use variables in a bunch of different ways (other than just forwarding to `Display`).

In your case, would you have a problem with adding the `T: Display` to your struct definition?

**Comment by droundy** [comment]
Yes, that works.  I didn't think to try that.  Thanks!

I see what you mean, I also had to add an Eq constraint, because my template used a method that required Eq.
