### ISSUE TITLE
Consider codegen using quote macro

### ISSUE THREAD

**Issue by casey** [djc/askama#129]
Thanks so much for askama! I'm using it to generate [my blog](https://rodarmor.com/blog), and I love it.

I just wanted to mention a technique for doing codegen that you might be interested in. It uses the [`quote!()` macro](https://github.com/dtolnay/quote), so you can write code inline inside the rust macro, using `#(..)` sequences to splice in values. You then turn the token lists output by the quote macros into strings, and write them to disk.

I used it [here](https://github.com/casey/uniblocks/blob/master/codegen/src/code.rs), to generate rust procedurally from the unicode standard. The output is [here](https://github.com/casey/uniblocks/blob/master/src/block.rs).

It's a nice alternative to writing strings directly, and is much more readable.

**Comment by djc** [comment]
Thanks for the suggestion! I did consider it, but it seemed to me that it wouldn't help that much in the case of Askama because it seems more focused on cases where more of the generated code comes from literals. Askama has pretty fine-grained code generation, and I feel the code generator is fairly well-structured and not that hard to comprehend.

Of course I wrote it, so I'm massively biased. You mention that `quote!()` is more readable, so do you have concrete parts of the code generator that you found hard to understand?

**Comment by casey** [comment]
I should preface this by saying that I didn't spend too much time on it, but I was looking at `visit_attr`, at found it a little hard to understand. I think it could be improved by using `quote!()`, but I definitely wouldn't claim to know for sure!

Could you explain what you mean by "where more of the generated code comes from literals"?

**Comment by djc** [comment]
I meant that larger chunks of the generated code are directly written down in the generating code, as literals (either strings, or tokens as used in `quote!()`). Whereas, as you see in `visit_attr()`, this code generator has really fine-grained chunks of stuff, spanning just a few tokens, that are added to the `TokenStream`. As an example, could you rewrite `visit_attr()` in `quote!()`?

**Comment by casey** [comment]
Yeah, I think that's definitely right.

I didn't try to get it to compile, but `visit_attr()` might look like this:

```
fn visit_attr(&mut self, obj: &Expr, attr: &str) -> Tokens {
    if let Expr::Var("loop") = *obj {
        match attr {
            "index" => quote!{(_loop_index + 1)},
            "index0" => quote!{_loop_index)},
            "first" => quote!{(_loop_index == 0)},
            _ => panic!("unknown loop variable"),
        }
    } else {
        quote! {
            #(self.visit_expr(obj)).#(syn::Ident::from(attr))
        }
    }
}
```

I left out `DisplayWrapped`. I might turn it into a wrapper like so:

```
#[derive(Clone)]
enum DisplayWrap {
    Wrapped(Tokens),
    Unwrapped(Tokens),
}
```

Since returning tuples feels a little awkward.

**Comment by djc** [comment]
Yeah, it feels like a wash to me. I initially wrote it this way in part because I've written a number of code generators in other languages, and I find them pretty straightforward to write.

So I think at this point I don't really want to put in the effort of changing it, but thanks for making me reconsider -- I might use `quote!()` more in a future project.

**Comment by casey** [comment]
Yup yup, totally fair!
