### ISSUE TITLE
Path confusion - especially with template inheritance

### ISSUE THREAD

**Issue by anowell** [djc/askama#26]
As [previously mentioned](https://github.com/djc/askama/issues/24#issuecomment-319904051), I was tripping over trying to move templates involving inheritance into subfolders. I would annotate the my template structs with the subfolder: `#[template(path = "terraform/variables_tf.j2")]`, but I'd get this as an error:

```
error[E0405]: cannot find trait `TraitFromvariables5ftf2ej2` in this scope
  --> src/templates/variables_tf.rs:15:10
   |
15 | #[derive(Template)] 
   |          ^^^^^^^^ not found in this scope
```

After battling with it a bit more, I came to understand that the child template file needed to also include the full path as `{% extends "terraform/variables_tf.j2" %}`. It felt unintuitive because I was writing that in a child template file that was in the same directory, so `{% extends "variables_tf.j2" %}` seemed more natural, though I do see the value in the extends path matching the path specified in the attribute. 

So primarily this is a papercut that could use a better error message and documentation, though I do wonder if it's worth considering a breaking change where "variables_tf.j2" could mean relative to current file and `/terraform/variables_tf.j2` could be relative to the template root (assuming the macro intrinsics are good enough to achieve that).

**Comment by djc** [comment]
With 21885c0, we now first search for a match relative to the current template, then fall back to the absolute path (relative to `$CARGO_MANIFEST_DIR/templates). This should make it more intuitive per your confusion, while minimizing the backwards compatibility impact.

(There is still some backwards compatibility impact, since `/sub/b.html` extending `a.html` will now use `/sub/a.html` where `/a.html` was meant and previously selected -- I'll make sure to write it up in the release notes.)
