### ISSUE TITLE
Filter on include

### ISSUE THREAD

**Issue by blakehawkins** [djc/askama#279]
I don't see a convenient way to do the following:

```
{%- include "blog-post.md" as blog -%}
{{ blog|markdown }}
```

**Comment by djc** [comment]
If some field in your context type itself implements `Template`, you could do `{{ posts.render()|markdown }}` though. I'm not sure filtering includes makes sense to me on a conceptual level. Is this supported in Jinja/Tera/Twig/other similar templating engines?

**Comment by blakehawkins** [comment]
Hey @djc I'm not sure. In jekyll, for example, you'd define a layout in html, and then author a markdown page, specifying a markdown parser and layout in the front matter.

In this case I'm just trying to include and markdown-render a static page (like a blog). As you said, for now I can `include_str!()` to provide it as a context parameter in the `Template`, but it would be good to have slightly more first-class support for this workflow.

Cheers,

**Comment by djc** [comment]
I think the problem here is just that files are not a first-class concept in Askama; they only exist at compile time as a source of template contents. Your design doesn't seem to fit in well with what I'm generally trying to achieve, and I can't really think of a good way to improve it. If you think of something, I'm happy to review/discuss further.

**Comment by djc** [comment]
Going to close this for now.

**Comment by sophie-h** [comment]
+1 for having the option to create part of the constant via markdown.

One thought I had was to have the option to run things like my `{% block content %}` through a filter or at least to have the option for it to be interpreted as markdown. Not sure if that would be a better solution?

**Comment by Kijewski** [comment]
This works as you would expect:

```rs
#[derive(askama::Template)]
#[template(
    source = r#"
        {{- include_str!("PATH/TO/README.md")|markdown -}}
    "#,
    ext = "html",
)]
struct Md;

fn main() {
    dbg!(Md.to_string());
}
```

Instead of `include_str!(…)` a field in the template would work as well. → https://djc.github.io/askama/filters.html#markdown

I don't know if there is a library that renders markdown at compile-time, but I don't think that would be too complicated to implement using e.g. comrak. But IMO that's out of scope of this of this project.

**Comment by sophie-h** [comment]
I don't see how you would use the template engine for markdown with this approach.
