### ISSUE TITLE
advice for dynamic template source at runtime

### ISSUE THREAD

**Issue by jokeyrhyme** [djc/askama#303]
Howdie, thanks for sharing this project!

I've been playing with it, and the happy path seems designed for cases where template files are static, have fixed paths at compile time, and don't change at runtime

I have a use case where I don't have the template contents at compile time, they are loaded at runtime

I noticed that internally, the `Source` enum can be either a `Path` or the `Source` contents itself, but this doesn't seem to be exposed in a way I can access

Is there an API that I can use to provide the template source at runtime?

Cheers!

**Comment by djc** [comment]
I guess it depends on what you're trying to achieve. Can you say more about your use case/why you'd want to use Askama for your project(s)?

The meat of Askama is basically a compiler that compiles a Jinja-like template language to Rust code. The Rust compiler then compiles the generated code to machine code. As far as I know, there aren't any good ways to run JIT-compile and run Rust code dynamically (perhaps miri could eventually do stuff like that?).

The closest solution I could think off is to compile the Askama templates into dynamically loadable libraries that you can then load in your main binary as you'd like.

Otherwise, maybe just using Tera (or any of the other dynamic template engines) makes more sense for your use case?

**Comment by jokeyrhyme** [comment]
My use case involves user-provided templates, so they cannot be known at compile-time

I'd missed this aspect of askama, which makes it awesome for other use cases but isn't a good fit for what I'm trying to do

Yep, tera has exactly the API I was thinking of, thanks! https://docs.rs/tera/1.1.0/tera/struct.Tera.html#method.render_str
