### ISSUE TITLE
Sources are parsed twice for no reason?

### ISSUE THREAD

**Issue by jonaspeter** [djc/askama#334]
I'm reading through the source code to learn more about derive macros, and I noticed something odd that could probably be improved if I understand it correctly. 

In the function `find_used_templates`  *(askama_derive/lib.rs:65)* the template sources are parsed to find all extended and imported templates. Then the unparsed sources are "returned". 

On line 35 the function is called, and the only thing that is done with the sources is to parse them again on line 38. 

Wouldn't it make sense to return the parsed sources instead? Also, why are you using a mutable parameter instead of returning the map normally?

If you think this is a valid improvement, I'll be happy to create a pull request :) 

If not, I'm sorry for the inconvenience of making you read this issue.

**Comment by djc** [comment]
I don't think it parses everything twice, but it does look like some things are parsed twice, indeed. I think the fix would be to check if `path` is already in `parsed` before parsing again in https://github.com/djc/askama/blob/master/askama_derive/src/lib.rs#L38? (Would be nice to run that through the tests and see how many duplicate parses it prevents.) PR very welcome.

I forget why exactly it doesn't return the parsed source, but I think it has to do with preventing more allocations than necessary and, while doing so, making sure the ownership is correct.

Thanks for reading the code, let me know if you have more questions! This was my first attempt at writing procedural macros and it ended up with a different style from more recent attempts; you might also like to look at https://github.com/djc/mendes/tree/master/mendes-macros and/or https://github.com/djc/corda-rpc/tree/master/oasis-amqp-macros. (Those don't try to cleanly format the source code inside the macro, because I now usually just use cargo-expand to look at the expanded source code.)

**Comment by jonaspeter** [comment]
I think you may have misunderstood my question. I mean that every source is already parsed here https://github.com/djc/askama/blob/master/askama_derive/src/lib.rs#L68 . The parse result is then consumed by the iterator and discarded. 

I tried returning the parse trees directly, but I can't do that because they reference the local source strings. 

As it turns out, that's not an easy problem to solve (at least for me), so I opened a question on StackOverflow. https://stackoverflow.com/questions/62102747/return-two-collections-where-one-references-the-other-in-rust I hope that's okay. 

Thank you for pointing me to your other projects with macros. I'm going to take a look at them :)

**Comment by djc** [comment]
This is what's called a self-referential borrow (well, in this case they're more like sibling-referential borrows), and they don't currently work unless you make some pretty complex contortions. Which for this case probably isn't worth it! So I guess we know now why it is like this.

**Comment by djc** [comment]
(Actually I do think it could be improved, I'll take a whack at it later.)

**Comment by jonaspeter** [comment]
It would be cool if you could figure something out. I'm still learning so much about borrows. 

It's also a little frightening to think about all the memory errors I've produced in C++ without being aware of them. It's so great how Rust won't let do anything like that.

**Comment by djc** [comment]
I spent some more time on this, but I don't think there is a way to do this with current Rust. The `sources` and `parsed` maps would have to grow simultaneously, but you can't hold references from one into the other while the other is being mutated (because the references might become invalid). So I'll close this issue for now.
