### ISSUE TITLE
[feature] Routerify

### ISSUE THREAD

**Issue by fimbault** [djc/askama#484]
Nice lib, would be awesome to get askama support for routerify

**Comment by djc** [comment]
I'd be happy to review a PR that adds an integration crate for this.

**Comment by fimbault** [comment]
great, will work on that when I get the time :-)

**Comment by dvtkrlbs** [comment]
Hmm taking a look at this issue and I dont think this needs a special integration since routerify handlers just returns `Response<Body>` and returning `Response::new(HelloTemplate { name: "tunahan"}.into())` just works. I can still create a PR with just tests to make sure we won't have any regressions though.

**Comment by dvtkrlbs** [comment]
Hmm we need to implement `From` trait on `Template` for `Body`. But the problem is implementing this violates orphan rules. So I am thinking of doing this in the actual `askama` crate via a future gate. Is that okay.

**Comment by dvtkrlbs** [comment]
Hmm I think we need to also generate From impls on code generation or I am missing something with generic impls.

**Comment by dvtkrlbs** [comment]
Hmm I think we cannot implement a trait for any type that implements some other traits without specialization (or i am horribly mistaken). What I am thinking is in derive if we are using with-routerify feature just generating the Into impl.
