### ISSUE TITLE
Update Gotham and Warp integrations

### ISSUE THREAD

**Issue by rushsteve1** [djc/askama#493]
Following up [from our discussion on Gitter](https://matrix.to/#/!LrVfbXAFPJgODjSOVC:gitter.im/$eEP4t0EwimyH9lWjOdssgpBjylOvBpzlPR4odtARmqM?via=gitter.im&via=matrix.org&via=mozilla.org), the `askama_gotham` needs to be updated to Gotham 0.6.0, and `askama_warp` needs to be updated to Warp 0.3.1, and releases need to be made to crates.io

Sidenote: the Rocket integration will likely need to be updated to Rocket 0.5 soon too.

**Comment by djc** [comment]
I published askama_gotham 0.12.0 (for Gotham 0.6). askama_warp does not need any updates, since 0.11.0 already supports warp 0.3.1. Support for the forthcoming Rocket release will be handled in #412/#495.

(P.S. Asking for all the things and the usage of "needs" here makes this feel a bit pushy. I also prefer to let users of each framework advocate for their own needs.)
