### ISSUE TITLE
How can I accept any number of arguments in a filter?

### ISSUE THREAD

**Issue by hwittenborn** [djc/askama#747]
Looking at the documentation for the [`format` filter](https://djc.github.io/askama/filters.html#format), it appears that it can take any number of arguments into the filter, which are then passed into the `format!` macro.

How can I get the same behavior without using an array or anything like that in my template? Looking through the [source of `format`](https://github.com/djc/askama/blob/main/askama/src/filters/mod.rs#L156), isn't helping, and I'm kind of just confused how it's working at all honestly

**Comment by Kijewski** [comment]
The documentation for [custom filters](https://djc.github.io/askama/filters.html#custom-filters) was just updated by @saona-raimundo. Did you have a look? Essentially:

```text
{{ lhs|my_filter }}          → my_filter(lhs)
{{ lhs|my_filter(a) }}       → my_filter(lhs, a)
{{ lhs|my_filter(a, b) }}    → my_filter(lhs, a, b)
{{ lhs|my_filter(a, b, c) }} → my_filter(lhs, a, b, c)
```

If you mean variadic arguments, they are not supported because Rust does not use variadic function either. Then you have to implement `my_filter2(lhs, a)`, `my_filter3(lhs, a, b)`, etc.

**Comment by Kijewski** [comment]
I think the question is answered.
